#include "main.h"

Texture2D tabut;
Texture2D tbbut;
Texture2D tcbut;
Texture2D tdbut;
Texture2D tebut;
Texture2D tfbut;
Texture2D tgbut;
Texture2D thbut;
Texture2D tjbut;
Texture2D tkbut;
Texture2D tibut;
Texture2D tlbut;
Texture2D tmbut;
Texture2D tnbut;
Texture2D tobut;
Texture2D tpbut;
Texture2D tqbut;
Texture2D trbut;
Texture2D tsbut;
Texture2D ttbut;
Texture2D tubut;
Texture2D tvbut;
Texture2D twbut;
Texture2D txbut;
Texture2D tybut;
Texture2D tzbut;
Texture2D t0but;
Texture2D t1but;
Texture2D t2but;
Texture2D t3but;
Texture2D t4but;
Texture2D t5but;
Texture2D t6but;
Texture2D t7but;
Texture2D t8but;
Texture2D t9but;
Texture2D tshiftbut;
Texture2D tspacebut;
Texture2D ttabbut;
Texture2D ttildebut;
Texture2D tcapbut;
Texture2D tctrlbut;
Texture2D taltbut;
Texture2D tKeys;
Texture2D tKeyboard_blank;
Texture2D tMouse1;
Texture2D tMouse2;
Texture2D tMouse3;
Texture2D tMouse4;
Texture2D tMouse5;
Texture2D tNoFocus;

void unload_textures(){
    UnloadTexture(tabut);
    UnloadTexture(tbbut);
    UnloadTexture(tcbut);
    UnloadTexture(tdbut);
    UnloadTexture(tebut);
    UnloadTexture(tfbut);
    UnloadTexture(tgbut);
    UnloadTexture(thbut);
    UnloadTexture(tjbut);
    UnloadTexture(tkbut);
    UnloadTexture(tibut);
    UnloadTexture(tlbut);
    UnloadTexture(tmbut);
    UnloadTexture(tnbut);
    UnloadTexture(tobut);
    UnloadTexture(tpbut);
    UnloadTexture(tqbut);
    UnloadTexture(trbut);
    UnloadTexture(tsbut);
    UnloadTexture(ttbut);
    UnloadTexture(tubut);
    UnloadTexture(tvbut);
    UnloadTexture(twbut);
    UnloadTexture(txbut);
    UnloadTexture(tybut);
    UnloadTexture(tzbut);
    UnloadTexture(t0but);
    UnloadTexture(t1but);
    UnloadTexture(t2but);
    UnloadTexture(t3but);
    UnloadTexture(t4but);
    UnloadTexture(t5but);
    UnloadTexture(t6but);
    UnloadTexture(t7but);
    UnloadTexture(t8but);
    UnloadTexture(t9but);
    UnloadTexture(tshiftbut);
    UnloadTexture(tspacebut);
    UnloadTexture(ttabbut);
    UnloadTexture(ttildebut);
    UnloadTexture(tcapbut);
    UnloadTexture(tctrlbut);
    UnloadTexture(taltbut);
    UnloadTexture(tKeys);
    UnloadTexture(tKeyboard_blank);
    UnloadTexture(tMouse1);
    UnloadTexture(tMouse2);
    UnloadTexture(tMouse3);
    UnloadTexture(tMouse4);
    UnloadTexture(tMouse5);
    UnloadTexture(tNoFocus);
}

//Add more for keys I didn't include myself, or remove if you are not using certain keys
//a-z, tilde, caps, shift, ctrl, alt, space, 0-9, keys,
void load_images(){
    Image iabut = LoadImage("images/abut.png"); tabut = LoadTextureFromImage(iabut); UnloadImage(iabut);
    Image ibbut = LoadImage("images/bbut.png"); tbbut = LoadTextureFromImage(ibbut); UnloadImage(ibbut);
    Image icbut = LoadImage("images/cbut.png"); tcbut = LoadTextureFromImage(icbut); UnloadImage(icbut);
    Image idbut = LoadImage("images/dbut.png"); tdbut = LoadTextureFromImage(idbut); UnloadImage(idbut);
    Image iebut = LoadImage("images/ebut.png"); tebut = LoadTextureFromImage(iebut); UnloadImage(iebut);
    Image ifbut = LoadImage("images/fbut.png"); tfbut = LoadTextureFromImage(ifbut); UnloadImage(ifbut);
    Image igbut = LoadImage("images/gbut.png"); tgbut = LoadTextureFromImage(igbut); UnloadImage(igbut);
    Image ihbut = LoadImage("images/hbut.png"); thbut = LoadTextureFromImage(ihbut); UnloadImage(ihbut);
    Image iibut = LoadImage("images/ibut.png"); tibut = LoadTextureFromImage(iibut); UnloadImage(iibut);
    Image ijbut = LoadImage("images/jbut.png"); tjbut = LoadTextureFromImage(ijbut); UnloadImage(ijbut);
    Image ikbut = LoadImage("images/kbut.png"); tkbut = LoadTextureFromImage(ikbut); UnloadImage(ikbut);
    Image ilbut = LoadImage("images/lbut.png"); tlbut = LoadTextureFromImage(ilbut); UnloadImage(ilbut);
    Image imbut = LoadImage("images/mbut.png"); tmbut = LoadTextureFromImage(imbut); UnloadImage(imbut);
    Image inbut = LoadImage("images/nbut.png"); tnbut = LoadTextureFromImage(inbut); UnloadImage(inbut);
    Image iobut = LoadImage("images/obut.png"); tobut = LoadTextureFromImage(iobut); UnloadImage(iobut);
    Image ipbut = LoadImage("images/pbut.png"); tpbut = LoadTextureFromImage(ipbut); UnloadImage(ipbut);
    Image iqbut = LoadImage("images/qbut.png"); tqbut = LoadTextureFromImage(iqbut); UnloadImage(iqbut);
    Image irbut = LoadImage("images/rbut.png"); trbut = LoadTextureFromImage(irbut); UnloadImage(irbut);
    Image isbut = LoadImage("images/sbut.png"); tsbut = LoadTextureFromImage(isbut); UnloadImage(isbut);
    Image itbut = LoadImage("images/tbut.png"); ttbut = LoadTextureFromImage(itbut); UnloadImage(itbut);
    Image iubut = LoadImage("images/ubut.png"); tubut = LoadTextureFromImage(iubut); UnloadImage(iubut);
    Image ivbut = LoadImage("images/vbut.png"); tvbut = LoadTextureFromImage(ivbut); UnloadImage(ivbut);
    Image iwbut = LoadImage("images/wbut.png"); twbut = LoadTextureFromImage(iwbut); UnloadImage(iwbut);
    Image ixbut = LoadImage("images/xbut.png"); txbut = LoadTextureFromImage(ixbut); UnloadImage(ixbut);
    Image iybut = LoadImage("images/ybut.png"); tybut = LoadTextureFromImage(iybut); UnloadImage(iybut);
    Image izbut = LoadImage("images/zbut.png"); tzbut = LoadTextureFromImage(izbut); UnloadImage(izbut);
    Image i0but = LoadImage("images/0but.png"); t0but = LoadTextureFromImage(i0but); UnloadImage(i0but);
    Image i1but = LoadImage("images/1but.png"); t1but = LoadTextureFromImage(i1but); UnloadImage(i1but);
    Image i2but = LoadImage("images/2but.png"); t2but = LoadTextureFromImage(i2but); UnloadImage(i2but);
    Image i3but = LoadImage("images/3but.png"); t3but = LoadTextureFromImage(i3but); UnloadImage(i3but);
    Image i4but = LoadImage("images/4but.png"); t4but = LoadTextureFromImage(i4but); UnloadImage(i4but);
    Image i5but = LoadImage("images/5but.png"); t5but = LoadTextureFromImage(i5but); UnloadImage(i5but);
    Image i6but = LoadImage("images/6but.png"); t6but = LoadTextureFromImage(i6but); UnloadImage(i6but);
    Image i7but = LoadImage("images/7but.png"); t7but = LoadTextureFromImage(i7but); UnloadImage(i7but);
    Image i8but = LoadImage("images/8but.png"); t8but = LoadTextureFromImage(i8but); UnloadImage(i8but);
    Image i9but = LoadImage("images/9but.png"); t9but = LoadTextureFromImage(i9but); UnloadImage(i9but);
    Image ishiftbut = LoadImage("images/shiftbut.png"); tshiftbut = LoadTextureFromImage(ishiftbut); UnloadImage(ishiftbut);
    Image ispacebut = LoadImage("images/spacebut.png"); tspacebut = LoadTextureFromImage(ispacebut); UnloadImage(ispacebut);
    Image itabbut = LoadImage("images/tabbut.png"); ttabbut = LoadTextureFromImage(itabbut); UnloadImage(itabbut);
    Image itildebut = LoadImage("images/tildebut.png"); ttildebut = LoadTextureFromImage(itildebut); UnloadImage(itildebut);
    Image icapbut = LoadImage("images/capbut.png"); tcapbut = LoadTextureFromImage(icapbut); UnloadImage(icapbut);
    Image ictrlbut = LoadImage("images/ctrlbut.png"); tctrlbut = LoadTextureFromImage(ictrlbut); UnloadImage(ictrlbut);
    Image ialtbut = LoadImage("images/altbut.png"); taltbut = LoadTextureFromImage(ialtbut); UnloadImage(ialtbut);
    Image iKeys = LoadImage("images/Keys.png"); tKeys = LoadTextureFromImage(iKeys); UnloadImage(iKeys);
    Image iKeyboard_blank = LoadImage("images/Keyboard_blank.png"); tKeyboard_blank = LoadTextureFromImage(iKeyboard_blank); UnloadImage(iKeyboard_blank);
    Image iMouse1 = LoadImage("images/Mouse1.png"); tMouse1 = LoadTextureFromImage(iMouse1); UnloadImage(iMouse1);
    Image iMouse2 = LoadImage("images/Mouse2.png"); tMouse2 = LoadTextureFromImage(iMouse2); UnloadImage(iMouse2);
    Image iMouse3 = LoadImage("images/Mouse3.png"); tMouse3 = LoadTextureFromImage(iMouse3); UnloadImage(iMouse3);
    Image iMouse4 = LoadImage("images/Mouse4.png"); tMouse4 = LoadTextureFromImage(iMouse4); UnloadImage(iMouse4);
    Image iMouse5 = LoadImage("images/Mouse5.png"); tMouse5 = LoadTextureFromImage(iMouse5); UnloadImage(iMouse5);
    Image iNoFocus = LoadImage("images/NoFocus.png"); tNoFocus = LoadTextureFromImage(iNoFocus); UnloadImage(iNoFocus);
}
